version: "3"
services:

  #backend
  backend-service:

    build: .

    container_name: ${BACKEND_SERVICE_NAME}

    env_file:
      - .env

    environment:
      - SQL_ALCHEMY_HOST=${DATABASE_SERVICE_NAME}
      - SQL_ALCHEMY_DATABASE=${DATABASE_NAME_DB}

    ports:
      - ${BACKEND_APP_PORT}:8080

    networks:
      - application

    depends_on:
      - database-service

  database-service:

    build: ${SERVICE_PATH}/deployments/database/.

    restart: always

    container_name: ${DATABASE_SERVICE_NAME}

    environment:
      - POSTGRES_USERNAME=${SQL_ALCHEMY_USERNAME}
      - POSTGRES_PASSWORD=${SQL_ALCHEMY_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME_DB}

    volumes:
      - ${SERVICE_PATH}/deployments/database/script.sql:/docker-entrypoint-initdb.d/script.sql

    ports:
      - ${SQL_ALCHEMY_PORT}:5432

    networks:
      - application

networks:
  application: