# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_project_and_responsible_detail import ResponseProjectAndResponsibleDetail  # noqa: F401,E501
from swagger_server import util


class ResponseProjectAndResponsibleData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, description: str=None, address: str=None, created_user: str=None, created_at: str=None, updated_user: str=None, updated_at: str=None, status: str=None, proyects: List[ResponseProjectAndResponsibleDetail]=None):  # noqa: E501
        """ResponseProjectAndResponsibleData - a model defined in Swagger

        :param id: The id of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type id: int
        :param name: The name of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type name: str
        :param description: The description of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type description: str
        :param address: The address of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type address: str
        :param created_user: The created_user of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type created_user: str
        :param created_at: The created_at of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type created_at: str
        :param updated_user: The updated_user of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type updated_user: str
        :param updated_at: The updated_at of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type updated_at: str
        :param status: The status of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type status: str
        :param proyects: The proyects of this ResponseProjectAndResponsibleData.  # noqa: E501
        :type proyects: List[ResponseProjectAndResponsibleDetail]
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'description': str,
            'address': str,
            'created_user': str,
            'created_at': str,
            'updated_user': str,
            'updated_at': str,
            'status': str,
            'proyects': List[ResponseProjectAndResponsibleDetail]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'address': 'address',
            'created_user': 'createdUser',
            'created_at': 'createdAt',
            'updated_user': 'updatedUser',
            'updated_at': 'updatedAt',
            'status': 'status',
            'proyects': 'proyects'
        }
        self._id = id
        self._name = name
        self._description = description
        self._address = address
        self._created_user = created_user
        self._created_at = created_at
        self._updated_user = updated_user
        self._updated_at = updated_at
        self._status = status
        self._proyects = proyects

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseProjectAndResponsibleData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseProjectAndResponsibleData of this ResponseProjectAndResponsibleData.  # noqa: E501
        :rtype: ResponseProjectAndResponsibleData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ResponseProjectAndResponsibleData.


        :return: The id of this ResponseProjectAndResponsibleData.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ResponseProjectAndResponsibleData.


        :param id: The id of this ResponseProjectAndResponsibleData.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ResponseProjectAndResponsibleData.


        :return: The name of this ResponseProjectAndResponsibleData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ResponseProjectAndResponsibleData.


        :param name: The name of this ResponseProjectAndResponsibleData.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ResponseProjectAndResponsibleData.


        :return: The description of this ResponseProjectAndResponsibleData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ResponseProjectAndResponsibleData.


        :param description: The description of this ResponseProjectAndResponsibleData.
        :type description: str
        """

        self._description = description

    @property
    def address(self) -> str:
        """Gets the address of this ResponseProjectAndResponsibleData.


        :return: The address of this ResponseProjectAndResponsibleData.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this ResponseProjectAndResponsibleData.


        :param address: The address of this ResponseProjectAndResponsibleData.
        :type address: str
        """

        self._address = address

    @property
    def created_user(self) -> str:
        """Gets the created_user of this ResponseProjectAndResponsibleData.


        :return: The created_user of this ResponseProjectAndResponsibleData.
        :rtype: str
        """
        return self._created_user

    @created_user.setter
    def created_user(self, created_user: str):
        """Sets the created_user of this ResponseProjectAndResponsibleData.


        :param created_user: The created_user of this ResponseProjectAndResponsibleData.
        :type created_user: str
        """

        self._created_user = created_user

    @property
    def created_at(self) -> str:
        """Gets the created_at of this ResponseProjectAndResponsibleData.


        :return: The created_at of this ResponseProjectAndResponsibleData.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this ResponseProjectAndResponsibleData.


        :param created_at: The created_at of this ResponseProjectAndResponsibleData.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_user(self) -> str:
        """Gets the updated_user of this ResponseProjectAndResponsibleData.


        :return: The updated_user of this ResponseProjectAndResponsibleData.
        :rtype: str
        """
        return self._updated_user

    @updated_user.setter
    def updated_user(self, updated_user: str):
        """Sets the updated_user of this ResponseProjectAndResponsibleData.


        :param updated_user: The updated_user of this ResponseProjectAndResponsibleData.
        :type updated_user: str
        """

        self._updated_user = updated_user

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this ResponseProjectAndResponsibleData.


        :return: The updated_at of this ResponseProjectAndResponsibleData.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this ResponseProjectAndResponsibleData.


        :param updated_at: The updated_at of this ResponseProjectAndResponsibleData.
        :type updated_at: str
        """

        self._updated_at = updated_at

    @property
    def status(self) -> str:
        """Gets the status of this ResponseProjectAndResponsibleData.


        :return: The status of this ResponseProjectAndResponsibleData.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ResponseProjectAndResponsibleData.


        :param status: The status of this ResponseProjectAndResponsibleData.
        :type status: str
        """

        self._status = status

    @property
    def proyects(self) -> List[ResponseProjectAndResponsibleDetail]:
        """Gets the proyects of this ResponseProjectAndResponsibleData.


        :return: The proyects of this ResponseProjectAndResponsibleData.
        :rtype: List[ResponseProjectAndResponsibleDetail]
        """
        return self._proyects

    @proyects.setter
    def proyects(self, proyects: List[ResponseProjectAndResponsibleDetail]):
        """Sets the proyects of this ResponseProjectAndResponsibleData.


        :param proyects: The proyects of this ResponseProjectAndResponsibleData.
        :type proyects: List[ResponseProjectAndResponsibleDetail]
        """

        self._proyects = proyects
